[package]
name = "bakezip"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "bakezip-cli"
path = "src/main.rs"

[dependencies]
encoding_rs = "0.8"
chardetng = "0.1"
